name: ISCROAdmin
main: com.zpj2008.myplugin.MyPlugin
version: 10.0-DEV-ONLY
commands:
  banme:
    description: 输入指令ban自己
  tps:
    description: nope
  kick-pl:
    description: nope
  ess:
    description: nope
  sreport:
    description: 向服务器反馈问题
  /health:
    description: 恢复血量